# NumPy - operacje arytmetyczne w Pythonie

Standardowe typy danych i procedury Pythona nie nadają się do poważnych zastosowań numerycznych. Konieczne było opracowanie zoptymalizowanych pod względem typowych operacji numerycznych typów danych i procedur. Stworzony został Numerical Python, zwany w skrócie NumPy. Podczas rozwoju tego pakietu kierowano się podejściem zastosowanym w takich językach jak Basis, MATLAB, rodzina języków APL, FORTRAN i innych. Tak więc NumPy jest biblioteką Pythona służącą do obliczeń naukowych. Dostarcza ona listę matematycznych funkcji użytecznych w takich zagadnieniach jak:
  
  * algebra liniowa,
  * transformacje Fouriera,
  * generowanie liczb losowych,
  * oraz wszystkie operacje na tablicach i macierzach, które są podstawowymi obiektami w Numpy.
  
Żeby można korzystać z dobrodziejstwa tej biblioteki należy ją zaimportować:

In [3]:
import numpy
# lub
import numpy as np 

## Tworzenie macierzy
Do stworzenia tablicy jedno-, dwu- i wielowymiarowej używamy funkcji **array**:

In [4]:
x = np.array([1,2,3]) # tablica jednowymiarowa
A = np.array([[1,2,3] , [4,5,6]]) # tablica dwuwymiarowa
B = np.array( [[[1,1,1],[1,1,1]], [[2,2,2],[2,2,2]]]) # wielowymiarowa

print(x)
print("\n \n")
print(A)
print("\n \n")
print(B)

[1 2 3]

 

[[1 2 3]
 [4 5 6]]

 

[[[1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]]]


Przy tworzeniu tablicy istnieje możliwość zadeklarowania jej typu:

In [5]:
z = np.array( [[1,0], [0,1]], dtype=complex) # tablica liczb zespolonych
print(z) 

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


Do tworzenia tablicy jednowymiarowej (wektora) składającego się z elementów z danego zakresu używamy polecenia **arange(start, stop, krok)**:

In [6]:
print(np.arange(10), end='\n \n')
print(np.arange(0, 10, 2), end='\n \n')
print(np.arange(0., 10, 0.5))

[0 1 2 3 4 5 6 7 8 9]
 
[0 2 4 6 8]
 
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


Jeśli chcemy wygenerować tablicę o określonej liczbie z danego przedziału, używamy funkcji **linspace**:

In [7]:
print(np.linspace(0., 10., 3), end='\n \n')
print(np.linspace(0., 1, 5) )

[ 0.  5. 10.]
 
[0.   0.25 0.5  0.75 1.  ]


Biblioteka Numpy oferuje wiele możliwości budowania typowych tablic:

In [8]:
print(np.ones((3,3)), '\n') # dwuwymiarowa tablica (3x3) wypełniona jedynkami
print(np.zeros((3,2)), '\n') # dwuwymiarowa tablica (3x2) wypełniona zerami
print(np.eye(4)) # macierz jednostkowa 4x4

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0.]
 [0. 0.]
 [0. 0.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Korzystając z powyższych funkcji możemy w łatwy sposób tworzyć dowolne macierze, zmieniając ich rozmiary.

In [9]:
print(np.arange(15).reshape(5,3), '\n')
print(np.linspace(0., 1, 15).reshape(5,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[[0.         0.07142857 0.14285714]
 [0.21428571 0.28571429 0.35714286]
 [0.42857143 0.5        0.57142857]
 [0.64285714 0.71428571 0.78571429]
 [0.85714286 0.92857143 1.        ]]


# Operacje na indeksach tablicy
Żeby odwołać się do konkretnej wartości tablicy należy użyć **[]** z odpowiednim indeksem (pamiętamy, że w Pythonie zaczynamy indeksować od 0).

In [10]:
x = np.arange(15)
print(x, '\n')
print(x[3], '\n')

A = np.arange(20).reshape(5,4)
print(A, '\n')
print(A[2, 3])
print(A[2][3], '\n') # równoważnie
print(A[2], '\n') # trzeci wiersz
print(A[:, 2]) # trzecia kolumna

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

3 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

11
11 

[ 8  9 10 11] 

[ 2  6 10 14 18]


Aby wyświetlić fragment tablicy od  $n-1$  do  $m-1$  elementów używamy składni: **tablica[n:m]**, analogicznie aby wyświetlić elementy tablicy pomiędzy  $n-1$ , a  $m-1$  przesuwając się o wartość  $k$  używamy składni **tablica[n:m:k]**. 


In [11]:
x = np.arange(15)
print(x, '\n')
print(x[3:11])
print(x[3:11:2], '\n')

A = np.arange(20).reshape(5,4)
print(A[2:4], '\n') # wiersze od trzeciego do czwartego
print(A[:,2:4], '\n') # trzecia i czwarta kolumnę
print(A[:,[2,3]]) # równoważnie

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

[ 3  4  5  6  7  8  9 10]
[3 5 7 9] 

[[ 8  9 10 11]
 [12 13 14 15]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]


Jak widać z powyższych przykładów, przecinek w nawiasach **[]** rozdziela poszczególne wymiary tablic.

In [12]:
print(A[1,1:5], '\n') # elementy z drugiego wiersza i od drugiej do piątej kolumny 
print(A[1:3, :2], '\n') # elementy od drugiego do trzeciego wiersza, 
                 # znajdujące się w kolumnach od pierwszej do drugiej
print(A[1,0:5:2]) # elementy drugiego wiersza i kolumny od pierwszej do piątej co dwie

[5 6 7] 

[[4 5]
 [8 9]] 

[4 6]


Tablice można też budować w oparciu o już istniejące:

In [13]:
A = np.arange(20).reshape(5,4)
print(A, '\n')

B = A[2:4, 2:]
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[[10 11]
 [14 15]]


# Zmiana rozmiaru, kształtu tablicy
Do zmiany rozmiaru tablicy już utworzonej służy funkcja: reshape. Operacja ta nie zmieni zawartości oryginalnej tablicy, pokaże jedynie jej elementy w zadanej postaci.

In [14]:
A = np.arange(8)
print(A,'\n')
print(A.reshape((2, 4)), '\n')
print(A)

[0 1 2 3 4 5 6 7] 

[[0 1 2 3]
 [4 5 6 7]] 

[0 1 2 3 4 5 6 7]


Aby zmienić kształt tablicy za pomocą funkcji reshape możemy zrobić tak:

In [15]:
A = np.arange(8)
print(A,'\n')
A = A.reshape((2, 4))
print(A)

[0 1 2 3 4 5 6 7] 

[[0 1 2 3]
 [4 5 6 7]]


lub użyć funkcję **resize**:

In [16]:
A = np.arange(8)
print(A,'\n')
A.resize(2, 4)
# print A.resize(2, 4), '\n'
print(A)

[0 1 2 3 4 5 6 7] 

[[0 1 2 3]
 [4 5 6 7]]


Do sprawdzenia wymiaru tablicy służy funkcja **shape**:

In [17]:
A = np.arange(20).reshape(5,4)
print(A.shape, '\n') # wymiar tablicy
print(A.shape[0], '\n') # pierwszy wymiar
print(A.shape[1], '\n') # drugi wymiar
print(A.size) # liczba wszystkich elementów w tablicy 

(5, 4) 

5 

4 

20


Transpozycja macierzy:

In [18]:
A = np.arange(8).reshape(2,4)
print(A, '\n')
print(A.T, '\n')
print(np.transpose(A))

[[0 1 2 3]
 [4 5 6 7]] 

[[0 4]
 [1 5]
 [2 6]
 [3 7]] 

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


Podobnie jak przy funkcji reshape aby zachować wynik transpozycji macierzy musimy go przypisać do nowej zmiennej.

In [19]:
print(A, '\n')
A = A.T
print(A)

[[0 1 2 3]
 [4 5 6 7]] 

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


Podobnie jest z poleceniem **swapaxes(tablica, oś1, oś2)**, które wyświetli zmienione wiersze z kolumnami dla tablicy dwuwymiarowej. Dla wielowymiarowych tablic zmieni ono elementy dla zadanych osi.

In [20]:
x = np.array([[1,2,3]])
print(x, '\n')
print(np.swapaxes(x,0,1), '\n')

x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(x, '\n')
print(np.swapaxes(x, 0, 2))

[[1 2 3]] 

[[1]
 [2]
 [3]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


Aby zmienić tablicę na jednowymiarową, możemy użyć polecenia:

In [21]:
A = np.arange(8).reshape(2,4)
print(A, '\n')
print(np.ravel(A), '\n')
print(A.reshape(-1,))

[[0 1 2 3]
 [4 5 6 7]] 

[0 1 2 3 4 5 6 7] 

[0 1 2 3 4 5 6 7]


# Podstawowe operacje na tablicach

  * dodawanie:

In [22]:
x = np.array([1,4,6,2,5])
v = np.arange(5)
print(x+v)
print(np.add(x, v), '\n') # równoważnie
print(x+1, '\n')

A = np.arange(15, 30).reshape((5, 3))
B = np.arange(15).reshape((5, 3))
print(A+B)
print(np.add(A, B), '\n')
print(A+5, '\n')

x = np.array([1,2,3])
print(A, '\n')
print(x, '\n')
print(np.add(A, x)) # dodawanie do każdego wiersza wektora x

[1 5 8 5 9]
[1 5 8 5 9] 

[2 5 7 3 6] 

[[15 17 19]
 [21 23 25]
 [27 29 31]
 [33 35 37]
 [39 41 43]]
[[15 17 19]
 [21 23 25]
 [27 29 31]
 [33 35 37]
 [39 41 43]] 

[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]] 

[[15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]] 

[1 2 3] 

[[16 18 20]
 [19 21 23]
 [22 24 26]
 [25 27 29]
 [28 30 32]]


* odejmowanie:

In [23]:
x = np.array([1,4,6,2,5])
v = np.arange(5)
print(x-v)
print(np.subtract(x, v), '\n') # równoważnie
print(x-1)

A = np.arange(15, 30).reshape((5, 3))
B = np.arange(15).reshape((5, 3))
print(A-B)
print(np.subtract(A, B), '\n')
print(A-1, '\n')

x = np.array([1,2,3])
print(np.subtract(A, x)) # odjęcie od każdego wiersza wektora x

[ 1  3  4 -1  1]
[ 1  3  4 -1  1] 

[0 3 5 1 4]
[[15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]]
[[15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]] 

[[14 15 16]
 [17 18 19]
 [20 21 22]
 [23 24 25]
 [26 27 28]] 

[[14 14 14]
 [17 17 17]
 [20 20 20]
 [23 23 23]
 [26 26 26]]


* mnożenie:

In [24]:
x = np.array([1,4,6,2,5])
v = np.arange(5)
print(x*5, '\n')
print(np.dot(x,v), '\n') # iloczyn skalarny
print(x*v, '\n' )# to nie, mnożony jest element przez element! 

A = np.array([[1, 3], [0, 6]])
print(A*5, '\n')

B = np.array([[-2, 6], [8, -2]])
print(np.dot(A, B), '\n')
print(A*B) # to nie, mnożony jest element przez element! 

[ 5 20 30 10 25] 

42 

[ 0  4 12  6 20] 

[[ 5 15]
 [ 0 30]] 

[[ 22   0]
 [ 48 -12]] 

[[ -2  18]
 [  0 -12]]


NumPy ma możliwość deklarowania macierzy, różnią się one w tym środowisku od tablic tym, że operacja mnożenia nie dotyczy mnożenia elementów, tylko klasycznego mnożenia macierzy:

In [25]:
A = np.matrix( ((2,3), (3, 5)) )
B = np.matrix( ((1,2), (5, -1)) )

print(A * B, '\n')
print(np.dot(A, B))

[[17  1]
 [28  1]] 

[[17  1]
 [28  1]]


  * potęgowanie:

In [26]:
x = np.array([1,4,6,2,5])
print(x, '\n')

print(x**2)
print(np.power(x, 2), '\n') # równoważnie

A = np.arange(9).reshape((3, 3))
print(A, '\n')
print(A**2, '\n') # kwadrat elementów tablicy
print(np.power(A, 2)) # równoważnie

[1 4 6 2 5] 

[ 1 16 36  4 25]
[ 1 16 36  4 25] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]] 

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


Więcej funkcji można znaleźć tutaj: [https://docs.scipy.org/doc/numpy/reference/routines.math.html].

## Porównania elementów tablic

In [27]:
A = np.arange(5, 20).reshape((5, 3))
B = np.arange(15).reshape((5, 3))

print(A < B, '\n')
print(A == A, '\n')
print(A == 17, '\n')
print(np.any( A > 17 ), '\n') # prawdziwe, jeśli każdy element z osobna spełnia warunek 
print(np.all( A > 17 )) # prawdziwe jeśli wszystkie elementy spełniają warunek

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [ True False False]] 

True 

False


## Łączenie i dzielenie tablic
Biblioteka <i>NumPy</i> daje nam narzędzia dzięki, którym możemy łączyć i dzielić tablice. Zaczniemy od omówienia problemu łączenia tablic:

In [28]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

print(x, '\n')
print(y, '\n')

# łączenie wierszowe
print(np.concatenate((x, y), axis=0), '\n')
print(np.vstack((x,y)), '\n')

# łączenie kolumnowe
print(np.concatenate((x,y.T), axis=1), '\n')
print(np.hstack((x,y.T)))

[[1 2]
 [3 4]] 

[[5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 5]
 [3 4 6]] 

[[1 2 5]
 [3 4 6]]


## Wybrane metody z algebry linowej
Do części funkcji typowych dla algebry liniowej możemy się odwołać po zaimportowaniu biblioteki **linalg** będącej integralną częścią biblioteki NumPy.

In [29]:
import numpy.linalg as alg 

Można tam znaleźć funkcję obliczającą:

* macierz odwrotną:

In [30]:
A = np.array([[1., 2.], [3., 4.]])
invA = alg.inv(A)
print(invA, '\n')
print(np.dot(A, invA))

[[-2.   1. ]
 [ 1.5 -0.5]] 

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


  * wyznacznik:

In [31]:
print(A, '\n')
print(alg.det(A))

[[1. 2.]
 [3. 4.]] 

-2.0000000000000004


  * ślad:

In [32]:
print(A, '\n')
print(np.trace(A))

[[1. 2.]
 [3. 4.]] 

5.0


  * normę dla macierz lub wektora:

In [33]:
print(alg.norm(A), '\n') # Euklidesowa
print(alg.norm(A, 'fro'), '\n') # Frobeniusa
print(alg.norm(A, np.inf), '\n') # maksimum

print(alg.norm(A, axis=0), '\n') # wierszy
print(alg.norm(A, axis=1), '\n') # kolumn

5.477225575051661 

5.477225575051661 

7.0 

[3.16227766 4.47213595] 

[2.23606798 5.        ] 



  * rozwiązywanie układów równań:

In [34]:
# 4*x_1 + x_2 = 10
# 3*x_1 = 7
A = np.array([[4,1], [3,0]])
b = np.array([10,7])
print(np.linalg.solve(A, b))

[2.33333333 0.66666667]


## Statystyka
<i>NumPy</i> oferuje dużo możliwości generacji liczb losowych. Poniżej podaję niektóre z nich, więcej można znaleźć tutaj:
[https://docs.scipy.org/doc/numpy/reference/routines.random.html]

In [35]:
# macierz losowa 3x2 (liczby z przedziału [0, 1)) 
print(np.random.rand(3,2), '\n')

# macierz losowa 2x3 o elementach z rozkładu N(mu, sigma^2) = N(1, 4)
print(2 * np.random.randn(2, 3) + 1, '\n')

# macierz losowa 3x3 o elementach całkowitych z przedziału [0, 5)
print(np.random.randint(5, size=(3, 3)), '\n')

# losowe wybranie 3 liczb z [0, 1, 2, 3, 4]
print(np.random.choice(5, 3, replace=False), '\n')

# rozkład wykładniczy (scale = 1/lambda)
print(numpy.random.exponential(scale=1.0, size=(2, 3)), '\n')

# rozkład geometryczny
print(np.random.geometric(p=0.35, size=(2,4)), '\n')

# rozkład normalny N(mu, sigma)
print(np.random.normal(0.0, 1, size=7), '\n')

# rozkład Poissona
print(np.random.poisson(5, 10), '\n')

# rozkład wielowymiarowy rozkład normalny
mean = [5, -5]
cov = [[10, -6], [-6, 5]]
print(np.random.multivariate_normal(mean, cov, 7), '\n')

[[0.24625813 0.34313692]
 [0.35368627 0.56733617]
 [0.46362098 0.98160295]] 

[[ 1.02363541  2.13178849 -1.79041225]
 [ 2.05254751  2.90277603  1.92362529]] 

[[2 1 2]
 [1 3 0]
 [2 2 0]] 

[0 4 1] 

[[0.89050408 1.01119496 0.8046013 ]
 [0.86661212 2.02408236 2.19577182]] 

[[3 2 1 1]
 [1 1 6 1]] 

[ 0.32043145 -0.06349327  1.47583663  0.62288413 -1.59784208 -1.11433287
  0.56754983] 

[5 9 7 1 8 4 5 7 6 4] 

[[  7.46250899  -4.36262526]
 [ 10.58519589 -10.13173619]
 [  6.85144762  -5.90550736]
 [  6.67801251  -5.16892309]
 [  1.77348574  -0.60026974]
 [  4.78940521  -4.85294183]
 [  5.52729527  -4.11993908]] 



Proste statystyki:

In [36]:
x = np.random.normal(2.0, 2.5, size=7)

print(x.max(),'\n') #maksymalna wartość

print(x.min(),'\n') # minimalna wartość 

print(x.sum(),'\n') # suma wszystkich elementów 

print(x.prod(),'\n') # iloczyn wszystkich elementów 

print(x.mean()) # średnia z wszystkich elementów
print(np.mean(x),'\n')

print(np.median(x),'\n') # mediana

print(x.std()) # odchylenie standardowe 
print(np.std(x),'\n')

print(x.var()) # wariancja
print(np.var(x))

9.85839762981904 

-0.38791855959015376 

27.082742034201804 

-969.6575066447582 

3.868963147743115
3.868963147743115 

3.1919958274735003 

3.127682358931426
3.127682358931426 

9.78239693837085
9.78239693837085


# Zadanie 1
Wygeneruj losową tablice 100 x 10, która będzie reprezentować 100 punktów w 10 wymiarowej przestrzeni. Napisz funkcję, która policzy odległość euklidesową pomiędzy każdą parą punktów, czy potrafisz zrobić to w jednej linijce, bez użycia żadnych pętli/wytworników pętli? Przypomnienie, dla dwóch wektorów  xx  i  yy  odległość euklidesową liczymy ze wzoru: 

$$
d(x,y)=\|x-y\|_2^2=\sum_{i=1}^n |x_i-y_i|^2.
$$

In [37]:

points = np.random.randint(10, size=(100, 10))

distances = [[np.linalg.norm(v1 - v2) for v2 in points] for v1 in points]
distances

[[0.0,
  12.884098726725126,
  9.273618495495704,
  13.152946437965905,
  11.832159566199232,
  12.84523257866513,
  13.638181696985855,
  16.1245154965971,
  9.899494936611665,
  15.0,
  12.206555615733702,
  14.491376746189438,
  11.489125293076057,
  12.206555615733702,
  12.489995996796797,
  15.905973720586866,
  10.535653752852738,
  10.246950765959598,
  15.066519173319364,
  13.674794331177344,
  11.0,
  12.649110640673518,
  15.748015748023622,
  8.426149773176359,
  13.527749258468683,
  9.1104335791443,
  9.797958971132712,
  6.244997998398398,
  11.704699910719626,
  12.767145334803704,
  12.449899597988733,
  10.583005244258363,
  13.674794331177344,
  11.224972160321824,
  14.2828568570857,
  5.656854249492381,
  14.106735979665885,
  12.0,
  13.379088160259652,
  13.076696830622021,
  16.30950643030009,
  6.48074069840786,
  12.529964086141668,
  11.135528725660043,
  10.583005244258363,
  9.695359714832659,
  10.583005244258363,
  12.68857754044952,
  7.874007874011811,

# Zadanie 2

Wygeneruj losową tablicę z wielowymiarowego rozkładu normalnego (procedura random.multivariate_normal), która będzie reprezentować 100 punktów w 5 wymiarowej przestrzeni. Napisz funkcję do normalizacji zbioru punktów (zrób to w jednej linijce, bez użycia pętli):

$$
x_{ij} = \frac{x_{ij}-\mu_j}{\sigma_j},
$$

gdzie  $μ_j$  to średnia, a  $σ_j$  to odchylenie standardowe po  $j$-tej kolumnie, zaś  $x_{ij}$  to  $j$-ta współrzędna  $i$ -tego wektora.

Policz średnią i macierz kowariancji tak przekształconych danych. Co zaobserwowałeś?

In [38]:
mean = np.random.randint(100, size=(5))
cov = np.random.randint(100, size=(5,5))
rand = np.random.multivariate_normal(mean, cov, 100)
norm=(rand-rand.mean(axis=0)/rand.std(axis=0))

print(np.cov(norm.T))
print(norm.mean(axis=0))


[[105.9474734   33.43790315  11.5878689   23.51225074  65.22520442]
 [ 33.43790315 126.56675035  56.12050872  64.20253127  54.36764288]
 [ 11.5878689   56.12050872  70.07534158  41.28187448  16.86920527]
 [ 23.51225074  64.20253127  41.28187448  91.22536771  38.97265025]
 [ 65.22520442  54.36764288  16.86920527  38.97265025  65.62396273]]
[62.78507935  4.13496302 69.86831082 58.39748878 38.48748827]


C:\Users\krzys\AppData\Local\Temp\ipykernel_12888\3508268149.py:3: RuntimeWarning: covariance is not positive-semidefinite.
  rand = np.random.multivariate_normal(mean, cov, 100)


# Zadanie 3

Wypełni 100-elementową tablicę liczbami losowymi naturalnymi z zakresu  $[5,15]$  i policz liczbę wystąpień tych liczb. Która z tych liczb najczęściej występuje w tak wygenerowanej tablicy?
Wskazówka: zobacz funkcje: bincount, argmax.

In [39]:
arr = np.random.randint(5,16,100)
count = np.bincount(arr)
print(count)
print(np.argmax(count))

[ 0  0  0  0  0  8 14 10 16  3  7 10  9  8  7  8]
8


# Zadanie 4

Korzystając z poniższego kodu zaimportuj dane **breast cancer**, który składa się z 2 elementów: macierzy  $X$  o wymiarach 569 x 30 oraz wektora  $y$ o długości 569. Macierz  $X$  opisuje badania 683 pacjentów, a wektor  $y$  ich diagnozy.

In [40]:
from sklearn.datasets import load_breast_cancer
X, y  = load_breast_cancer(return_X_y=True)
print(X.shape)
print(y.shape)

(569, 30)
(569,)


Za pomocą biblioteki **numpy** przenumeruj wektor  $y$ , tzn zamień wartości $0$ i $1$ na $-1$ i $+1$. Przeskaluj macierz  $X$ , tak żeby wartości w każdej kolumnie mieściły się w zakresie  $[0,1]$ , innymi słowy przeskaluj niezależnie każdą kolumnę  $X_i$  według poniższej procedury: 

$$
X_i=\frac{X_i-min(X_i)}{max(X_i)-min(X_i)}.
$$

In [41]:
y = np.where(y == 0, -1, 1)
Xmin = np.min(X, axis=0)
Xmax = np.max(X, axis=0)
z = (X - Xmin) / (Xmax - Xmin)
print(z)

[[0.52103744 0.0226581  0.54598853 ... 0.91202749 0.59846245 0.41886396]
 [0.64314449 0.27257355 0.61578329 ... 0.63917526 0.23358959 0.22287813]
 [0.60149557 0.3902604  0.59574321 ... 0.83505155 0.40370589 0.21343303]
 ...
 [0.45525108 0.62123774 0.44578813 ... 0.48728522 0.12872068 0.1519087 ]
 [0.64456434 0.66351031 0.66553797 ... 0.91065292 0.49714173 0.45231536]
 [0.03686876 0.50152181 0.02853984 ... 0.         0.25744136 0.10068215]]


# Biblioteka Pandas

**Pandas** jest darmową biblioteką języka Python, która służy do analizy danych. Zawiera łatwe w użyciu struktury i narzędzia do analizy danych spotykane w języku R.

Biblioteka ta pozwala między innymi na:
  
  * tworzenie własnych danych w odpowiednich strukturach,
  * importowanie i eksportowanie danych do różnych plików,
  * przygotowanie danych do analizy (pozbycie się anomalii w danych, np. brakujących wartości),
  * analizę danych,
  * prezentację danych.

Do instalacji tej biblioteki można użyć procedury **pip** albo **conda** [http://pandas.pydata.org/pandas-docs/stable/install.html]

Aby skorzystać z biblioteki pandas należy ją wcześniej zaimportować, np.:

In [42]:
# import pandas
import pandas as pd

print(pd.__version__) # wersja biblioteki
%matplotlib inline

1.4.1


## Struktury danych

Biblioteka pandas wprowadza dwie nowe struktury danych do Pythona: **Series** i **DataFrame**.

1. **Serie**

Seria to jednowymiarowy obiekt podobny do tablicy, listy, który może zawierać różnego rodzaju dane (liczby całkowite, zmiennoprzecinkowe, ciągi, obiekty Pythona, itd.). Każdy element serii ma przypisany indeks/etykietę (domyślnie od 0 do N, gdzie N jest długość serii minus 1).

In [43]:
from pandas import Series, DataFrame
import pandas as pd
s = pd.Series([7, 'Heisenberg', 3.14, -1789710578, 'Happy Eating!'])
print(s)

0                7
1       Heisenberg
2             3.14
3      -1789710578
4    Happy Eating!
dtype: object


Alternatywnie, można zdefiniować indeksy elementów serii w trakcje jej definicji:

In [44]:
import numpy as np

# Series(dane, index=indeks)
s = Series(np.random.randn(5), index=['a', 'b', 'c', 'i', 'e'])
print(s)

a    0.731445
b   -1.296628
c   -0.354773
i   -0.122137
e    0.956644
dtype: float64


Konstruktor **Series** może przetwarzać słowniki Pythona:

In [45]:
d = {'a' : 0., 'b' : 1., 'c' : 2.}
print(Series(d))

a    0.0
b    1.0
c    2.0
dtype: float64


In [46]:
print(Series(d, index=['b', 'c', 'd', 'a']))

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64


In [47]:
print(Series(1, index=['a', 'b', 'c', 'd', 'e']), '\n')
print(Series(1., index=['a', 'b', 'c', 'd', 'e']))

a    1
b    1
c    1
d    1
e    1
dtype: int64 

a    1.0
b    1.0
c    1.0
d    1.0
e    1.0
dtype: float64


## 1.1 Odwoływanie się do elementów serii

Struktura Series działa jak tablica. Można odwołać się do poszczególnego elementu serii za pomocą indeksu, używać logicznego indeksowania, itd.:

In [48]:
s = Series(np.random.randn(5), index=['a', 'b', 'c', 'i', 'e'])
print(s, '\n')

print(s[0], s[3])

a   -1.122792
b    0.074134
c   -0.065522
i   -0.910618
e    0.584105
dtype: float64 

-1.1227921628382536 -0.910617610022983


In [49]:
print(s[s > 0.5], '\n')
print(s[s > s.mean()])

e    0.584105
dtype: float64 

b    0.074134
c   -0.065522
e    0.584105
dtype: float64


## 1.2 Zmiana wartości wybranych elementów

In [50]:
s = Series(np.random.randn(5), index=['a', 'b', 'c', 'i', 'e'])
print(s, '\n')
print("stara wartosc:",  s[0])
s[0] = 10. 
print("nowa wartosc:",  s[0], '\n')

print("stara wartosc:",  s['b'])
s['b'] = 15. 
print("nowa wartosc:",  s['b'])

a   -0.000523
b   -0.765484
c    0.676786
i    0.633320
e    1.551228
dtype: float64 

stara wartosc: -0.0005228444066637936
nowa wartosc: 10.0 

stara wartosc: -0.7654837499783728
nowa wartosc: 15.0


In [51]:
s = Series(np.random.randn(5), index=['a', 'b', 'c', 'i', 'e'])
print("stare:\n",  s, '\n')
s[s < s.mean()] = 1
print("nowe:\n",  s)

stare:
 a    0.695724
b   -1.909846
c    0.106486
i   -0.905921
e    0.709052
dtype: float64 

nowe:
 a    0.695724
b    1.000000
c    0.106486
i    1.000000
e    0.709052
dtype: float64


## 1.5 Niezdefiniowane wartości, obiekty

In [52]:
cities = Series({'Chicago': 1000, 'New York': 1300, 'Portland': 900,
                 'San Francisco': 1100, 'Austin': 450, 'Boston': None})
print(cities, '\n')

print('Seattle' in cities)
print('San Francisco' in cities)

Chicago          1000.0
New York         1300.0
Portland          900.0
San Francisco    1100.0
Austin            450.0
Boston              NaN
dtype: float64 

False
True


In [53]:
print(cities, '\n')
print(cities.notnull()) # które są zdefiniowane

Chicago          1000.0
New York         1300.0
Portland          900.0
San Francisco    1100.0
Austin            450.0
Boston              NaN
dtype: float64 

Chicago           True
New York          True
Portland          True
San Francisco     True
Austin            True
Boston           False
dtype: bool


In [54]:
print(cities.isnull()) # które nie są zdefiniowane

Chicago          False
New York         False
Portland         False
San Francisco    False
Austin           False
Boston            True
dtype: bool


In [55]:
print(cities[cities.isnull()]) # tylko te które nie są zdefiniowane 
cities[cities.isnull()] = 1
print() 
print(cities.isnull())
print()
print(cities)

Boston   NaN
dtype: float64

Chicago          False
New York         False
Portland         False
San Francisco    False
Austin           False
Boston           False
dtype: bool

Chicago          1000.0
New York         1300.0
Portland          900.0
San Francisco    1100.0
Austin            450.0
Boston              1.0
dtype: float64


# 2. DataFrame

<i>DataFrame</i> to struktura danych składa się z wierszy i kolumn, podobna do arkusza kalkulacyjnego, baz danych, tabeli 2-wymiarowej lub data.frame obiektu z języka R.

Poniżej przedstawiam kilka sposobów definiowania struktury DataFrame:

  * ze słownika list/tablic

In [56]:
d = {'one' : [1., 2., 3., 4.],
     'two' : [4., 3., 2., 1.]}
print(DataFrame(d))
DataFrame(d)

   one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  1.0


one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  1.0

In [57]:
data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
        'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions', 'Lions', 'Lions'],
        'wins': [11, 8, 10, 15, 11, 6, 10, 4],
        'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
football = pd.DataFrame(data, columns=['year', 'team', 'wins', 'losses'])
football

year     team  wins  losses
0  2010    Bears    11       5
1  2011    Bears     8       8
2  2012    Bears    10       6
3  2011  Packers    15       1
4  2012  Packers    11       5
5  2010    Lions     6      10
6  2011    Lions    10       6
7  2012    Lions     4      12

## 2.1 Podstawowe informacje
Biblioteka pandas ma wiele funkcji, które dostarczają nam podstawowej informacji na DataFrame. Jedną z takich funkcji jest metoda **info**.

In [58]:
data = [{'a': 1, 'b': 2}, 
         {'a': 5, 'b': 10, 'c': 20}]
df = DataFrame(data)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       2 non-null      int64  
 1   b       2 non-null      int64  
 2   c       1 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 176.0 bytes


## 2.2 Wybieranie rekordów, kolumn, elementów

Jak już wspomniałem strukturę DataFrame możemy traktować jako grupę/tablicę serii, które dzielą indeks (w tym przypadku nagłówki kolumn). Dzięki temu możemy w łatwy sposób wybrać konkretne rekordy.

In [59]:
data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
        'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions', 'Lions', 'Lions'],
        'wins': [11, 8, 10, 15, 11, 6, 10, 4],
        'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
football = pd.DataFrame(data, columns=['year', 'team', 'wins', 'losses'])
print (football)

football.head(3)

   year     team  wins  losses
0  2010    Bears    11       5
1  2011    Bears     8       8
2  2012    Bears    10       6
3  2011  Packers    15       1
4  2012  Packers    11       5
5  2010    Lions     6      10
6  2011    Lions    10       6
7  2012    Lions     4      12


year   team  wins  losses
0  2010  Bears    11       5
1  2011  Bears     8       8
2  2012  Bears    10       6

In [60]:
football['year'].head(4)

0    2010
1    2011
2    2012
3    2011
Name: year, dtype: int64

In [61]:
football.tail(3)

year   team  wins  losses
5  2010  Lions     6      10
6  2011  Lions    10       6
7  2012  Lions     4      12

Możemy też modyfikować DataFrame na podstawie wybranej kolumny.

In [62]:
football.set_index('team')

year  wins  losses
team                       
Bears    2010    11       5
Bears    2011     8       8
Bears    2012    10       6
Packers  2011    15       1
Packers  2012    11       5
Lions    2010     6      10
Lions    2011    10       6
Lions    2012     4      12

Aby wybrać którąś z kolumn należy użyć jej nazwy:

In [63]:
data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
        'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions', 'Lions', 'Lions'],
        'wins': [11, 8, 10, 15, 11, 6, 10, 4],
        'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
football = pd.DataFrame(data, columns=['year', 'team', 'wins', 'losses'])

football['year'] # wybieramy kolumnę 'year'

0    2010
1    2011
2    2012
3    2011
4    2012
5    2010
6    2011
7    2012
Name: year, dtype: int64

In [64]:
football.year

0    2010
1    2011
2    2012
3    2011
4    2012
5    2010
6    2011
7    2012
Name: year, dtype: int64

In [65]:
football[['year', 'wins']]

year  wins
0  2010    11
1  2011     8
2  2012    10
3  2011    15
4  2012    11
5  2010     6
6  2011    10
7  2012     4

Do wybierania wierszy/obserwacji służy funkcja **loc** (indeksowanie oparte na etykietach) lub **iloc** (indeksowanie oparte na pozycji).

In [66]:
football.loc[0]

year       2010
team      Bears
wins         11
losses        5
Name: 0, dtype: object

In [67]:
football.loc[[0,3]]

year     team  wins  losses
0  2010    Bears    11       5
3  2011  Packers    15       1

# 2.3 Podstawowe operacje na DataFrame

In [68]:
football[football.wins > 10]

year     team  wins  losses
0  2010    Bears    11       5
3  2011  Packers    15       1
4  2012  Packers    11       5

In [69]:
football['wins'].max()

15

In [70]:
football[['wins', 'losses']].mean()

wins      9.375
losses    6.625
dtype: float64

In [71]:
football['wins'] = 0
football.at[5, 'losses'] = 0
football

year     team  wins  losses
0  2010    Bears     0       5
1  2011    Bears     0       8
2  2012    Bears     0       6
3  2011  Packers     0       1
4  2012  Packers     0       5
5  2010    Lions     0       0
6  2011    Lions     0       6
7  2012    Lions     0      12

## 2.6 Importowanie i eksportowanie danych

  * eksport to CSV:

In [72]:
data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
        'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions', 'Lions', 'Lions'],
        'wins': [11, 8, 10, 15, 11, 6, 10, 4],
        'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
football = pd.DataFrame(data, columns=['year', 'team', 'wins', 'losses'])

football.to_csv('dane.csv', index=False)

  * import z CSV:

In [73]:
pd.read_csv('dane.csv')

year     team  wins  losses
0  2010    Bears    11       5
1  2011    Bears     8       8
2  2012    Bears    10       6
3  2011  Packers    15       1
4  2012  Packers    11       5
5  2010    Lions     6      10
6  2011    Lions    10       6
7  2012    Lions     4      12

Więcej informacji na temat biblioteki pandas można znaleźć tutaj: [http://pandas.pydata.org]

# Zadanie 5

Zaimportuj dane z pliku ,,airports.csv'' i wykonaj na nich poniższe polecenia:

  * wybierz nazwy państw ostatnich 12 lotnisk w tabeli,
  * wybierz wiersz o indeksie 1 korzystając z indeksera .loc oraz .iloc (porównaj otrzymane wyniki),
  * wybierz wszystkie lotniska w Polsce,
  * wybierz wszystkie lotniska, których nazwa różni się od nazwy miasta, w którym się znajdują.
  * przelicz wartości wysokości na metry i zapisz zmodyfikowaną kolumnę w miejsce starej (w naszej tabeli wysokość jest podana w   * stopach nad poziomem morza; jedna stopa angielska równa się 30,48 cm),
  * znajdź wszystkie państwa, w których znajduje się wyłącznie 1 lotnisko (zobacz procedurę .unique()).

In [86]:
df = pd.read_csv('Data/airports.csv', names=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'])
df

1                                  2                3  \
0        1                             Goroka           Goroka   
1        2                             Madang           Madang   
2        3                        Mount Hagen      Mount Hagen   
3        4                             Nadzab           Nadzab   
4        5         Port Moresby Jacksons Intl     Port Moresby   
...    ...                                ...              ...   
8102  9537    Mansons Landing Water Aerodrome  Mansons Landing   
8103  9538               Port McNeill Airport     Port McNeill   
8104  9539       Sullivan Bay Water Aerodrome     Sullivan Bay   
8105  9540               Deer Harbor Seaplane      Deer Harbor   
8106  9541  San Diego Old Town Transit Center        San Diego   

                     4    5     6          7           8     9    10 11  \
0     Papua New Guinea  GKA  AYGA  -6.081689  145.391881  5282  10.0  U   
1     Papua New Guinea  MAG  AYMD  -5.207083  145.788700    20  10.0  U   
2     Papua New Guinea  HGU  AYMH  -5.826789  144.295861  5388  10.0  U   
3     Papua New Guinea  LAE  AYNZ  -6.569828  146.726242   239  10.0  U   
4     Papua New Guinea  POM  AYPY  -9.443383  147.220050   146  10.0  U   
...                ...  ...   ...        ...         ...   ...   ... ..   
8102            Canada  YMU    \N  50.066667 -124.983333     0  -8.0  A   
8103            Canada  YMP    \N  50.575556 -127.028611   225  -8.0  A   
8104            Canada  YTG    \N  50.883333 -126.833333     0  -8.0  A   
8105     United States  DHB    \N  48.618397 -123.005960     0  -8.0  A   
8106     United States  OLT    \N  32.755200 -117.199500     0  -8.0  A   

                        12  
0     Pacific/Port_Moresby  
1     Pacific/Port_Moresby  
2     Pacific/Port_Moresby  
3     Pacific/Port_Moresby  
4     Pacific/Port_Moresby  
...                    ...  
8102     America/Vancouver  
8103     America/Vancouver  
8104     America/Vancouver  
8105   America/Los_Angeles  
8106   America/Los_Angeles  

[8107 rows x 12 columns]

In [100]:
print(df['4'].tail(12).unique())

print(df.loc[1])
print()
print(df.iloc[1])

print(df[df['4'] == 'Poland'])

print(df[df['2'] != df['3']])

df['9'] = (df['9'] * 30.48)/100
print(df['9'])

print(pd.unique(df['4']))

['Cambodia' 'Taiwan' 'Australia' 'United States' 'Spain' 'Canada']
1                        2
2                   Madang
3                   Madang
4         Papua New Guinea
5                      MAG
6                     AYMD
7                -5.207083
8                 145.7887
9                 1.858061
10                    10.0
11                       U
12    Pacific/Port_Moresby
Name: 1, dtype: object

1                        2
2                   Madang
3                   Madang
4         Papua New Guinea
5                      MAG
6                     AYMD
7                -5.207083
8                 145.7887
9                 1.858061
10                    10.0
11                       U
12    Pacific/Port_Moresby
Name: 1, dtype: object
         1                                        2               3       4  \
658    667                                   Babice          Warsaw  Poland   
659    668                              Lech Walesa          Gdansk  Poland   
6

# Dane do kolejnych zadań
Wczytanie dancyh:

  * Powinieneś być w stanie zobaczyć wszystkie kolumny i 10 wierszy danych:
  * survival – Survival (0 = No; 1 = Yes)
  * pclass – Passenger Class (1 = 1st; 2 = 2nd; 3 = 3rd)
  * sex – Sex
  * age – Age
  * sibsp – Number of Siblings/Spouses Aboard
  * parch – Number of Parents/Children Aboard
  * ticket – Ticket Number
  * fare – Passenger Fare
  * cabin – Cabin
  * embarked – Port of Embarkation (C = Cherbourg; Q = Queenstown; S = Southampton)


In [102]:
df = pd.read_csv('http://stamfordresearch.com/wp-content/uploads/2016/08/Titanic.csv') 
print(df.shape)
df.head()

HTTPError: HTTP Error 403: Forbidden

In [ ]:
df.columns

# Zadanie 6

Usuń kolumny: "PassengerId", "Name" i "Ticket".

Powody:

  * PassengerId - jest to unikalny numer
  * Imię - nie ma wpływu na predykcje
  * Bilet - wygląda niechlujnie i jest losowe

# Następnie musimy spojrzeć na kolumnę Cabin.

Następnie musimy spojrzeć na kolumnę Cabin. Będziemy leniwi i zmienimy wartości na Tak lub Nie (w zależności czy posiadał kabinę). Lepszym sposobem na to może być podzielenie opisu tak aby uzyskać pierwszą literę, ponieważ zwykle oznacza ona, na którym pokładzie znajdowała się kabina. Może to być użyteczne przy predykcji (ale my na razie jej nie wykonujemy).

In [ ]:
df.loc[df.Cabin.isnull()]

# Zadanie 7
Utwórz nową kolumną o nazwie HasCabin, która zawiera 1 jeżeli ktoś miał swoją kabinę i 0 jeśli nie.

# Zadanie 8
Usuń brakujące wartości

# Matplotlib - rysowanie wykresów w Pythonie

**Matplotlib** jest biblioteką do tworzenia wysokiej jakości wykresów dla języka Python i jego rozszerzenia numerycznego NumPy. Umożliwia prezentację danych w różnych formatach (np. PNG, PDF, XLS). Zapewnia kontrolę nad wyglądem, stylami i właściwościami wykresów, pracę w środowisku interaktywnym, jak i możliwość osadzania wyników w aplikacjach destkopowych czy webowych.

Funkcje i narzędzia tej biblioteki są napisane w taki sposób aby jak najbardziej odzwierciedlały metody rysowania wykresów z języka MatLab, dzięki czemu użytkownicy Matlaba w łatwy sposób mogą przenieść się do języka Python.
Niektóre zalety korzystania z Pythona, NumPy i matplotlib nad MatLabem:
  
  * nowoczesny język programowania w pełni funkcjonalny obiektowo, odpowiedni do tworzenia oprogramowania na dużą skalę,
  * darmowy (open source),
  * wsparcie SVG.

Aby skorzystać z biblioteki matplotlib należy ją wcześniej zaimportować, np.:

In [ ]:
import matplotlib.pyplot as plt
# from matplotlib import pyplot as plt

%matplotlib inline

# Pierwszy wykres

In [ ]:
plt.plot([1, 5, 2, 7, 4, 1]) # wartości funkcji
plt.show()

In [ ]:
plt.plot([1, 2, 4, 7], [-1, 3, -2, 10])
plt.show()

Własności wykresów
Za pomocą specjalnych poleceń można też zmieniać właściwości wykresów, takie jak np.: rodzaj linii, kolor, czy też symbole punktów.
Rodzaje linii:
  
  * **\-** - ciągła,
  * **:** - punktowa,
  * **-.** - kropka-kreska,
  * **--** - kreskowana.

Kolory:

  * **y** - yellow,
  * **m** - magenta,
  * **c** - cyan,
  * **r** - red,
  * **g** - green,
  * **b** - blue,
  * **w** - white,
  * **k** - black.

Symbole:

  * **.** - punkt,
  * **o** - kółko,
  * **x** - x,
  * **\+** - plus,
  * ** \* ** - gwiazdka,
  * **s** - kwadraty,
  * **d** - romb,
  * **v** - trójkąt w dół,
  * **^** - trójkąt w górę,
  * **<** - trójkąt w lewo,
  * **\>** - trójkąt w prawo,
  * **p** - pięciokąt,
  * **h** - sześciokąt.

In [ ]:
import numpy as np

x = np.arange(0., 5., 0.2)

plt.plot(x, x, 'r--', x, x**2, 'bs', x, x**3, 'g^')
plt.show()

In [ ]:
x = [1,2,3,4]
y = [20, 21, 20.5, 20.8]

plt.plot(x, y, linestyle="dashed", marker="o", color="green")

# ustawienie granic osi X, 
plt.xlim(0.5,4.5)
plt.ylim(19.8,21.2)

plt.show()

In [ ]:
x = np.linspace(0, 20, 1000)
y1 = np.sin(x)
y2 = np.cos(x)

# rozmiar czcionki
plt.rc("font", size=10)

# dodanie legendy
plt.plot(x, y1, '-b', label=r'$\sin(x)$')
plt.plot(x, y2, '-r', label='cosine')
plt.legend(loc='upper right') # pozycja legendy
# plt.legend(loc='upper left', frameon=False)
plt.ylim(-1.5, 2.0)

plt.title("Dwa wykresy", size=20)

plt.show()

Więcej na temat wyszczególnienia obiektów na wykresie odsyłam do dokumntacji: [http://matplotlib.org/users/annotations_guide.html]


#  Statystyka


In [ ]:
inFile = 'http://ww2.amstat.org/publications/jse/datasets/babyboom.dat.txt'
data = pd.read_csv(inFile, sep='[ ]+', header=None, engine='python',names= ['sex', 'Weight', 'Minutes'])
df = data[['Minutes', 'sex', 'Weight']]

  * Narysujmy dane <tt>df.Weight.values</tt> jako szereg czasowy

In [ ]:
x=df.Weight.values
plt.scatter(np.arange(len(x)), x)
plt.show()

 Narysujmy histogram dla <tt>df.Weight.values</tt>

In [ ]:
plt.hist(x, bins=25)
plt.show()

Narysujmy gęstość dla <tt> df.Weight.values</tt> (estymacja jądrowa):

In [ ]:
import seaborn as sns
sns.kdeplot(x)
plt.show()

Narysujmy dystrybuantę empiryczną dla </tt> df.Weight.values<tt>

In [ ]:
from scipy import stats
plt.plot(stats.cumfreq(x,numbins=25)[0])
plt.show()

Narysujmy wykres pudełkowy dla <tt>df.Weight.values</tt>

In [ ]:
plt.boxplot(x, sym='*')
plt.show()

Narysujmy wykres skrzypcowy dla <tt>df.Weight.values</tt>

In [ ]:
sns.violinplot(x)
plt.show()

# Zadanie
Proszę podzielić próbkę na dwie grupy ze względu na płeć (kolumna ``sex'') i narysować dla nich:
<ul>
<li>wykres w kształcie szeregu czasowego</li>
<li>histogramy</li>
<li>estymacje gęstości</li>
<li>dystrybuanty empiryczne</li>
<li>wykresy pudełkowe</li>
<li>wykresy skrzypcowe</li>
</ul>

# Zadanie 9


## Reguła Trzech Sigm
Reguła Trzech Sigm dla danego rozkładu normalnego $N(mean,\sigma)$ oznacza, że w przedziale $[mean-3\sigma,mean+3\sigma]$ znajduje się 99.7\% wszystkich obserwacji.

Napisz program, który:

  * rysuje gęstość rozkładu normalnego o zadanych parametrach $mean$ i $\sigma$,
  * wylicza pole pod krzywą
  * zaznacza obszar po krzywą

Policz prawdopodobieństwa:

  * $P(X \in [mean-\sigma,mean+\sigma])$
  * $P(X \in [mean-2\sigma,mean+2\sigma])$
  * $P(X \in [mean-3\sigma,mean+3\sigma])$

